# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

arc:
  ai:
    clients:
      - id: ministral
        modelName: ministral-3:3b
        client: ollama
        url: http://localhost:11434